name: CI/CD Pipeline

on:
  push:
    branches:
      - master 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ApiHelm/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/dockerapihelm:latest

    - name: Checkout Helm Chart Repo
      uses: actions/checkout@v2
      with:
        repository: sebas99cp/ApiHelm-chart
        path: ApiHelm-chart

    - name: Update Helm chart version
      run: |
        # Incrementa la versión del chart en Chart.yaml
        VERSION=$(grep '^version:' ApiHelm-chart/Chart.yaml | awk '{print $2}')
        NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF += 1 ; print}')
        sed -i "s/^version:.*/version: $NEW_VERSION/" ApiHelm-chart/Chart.yaml
        
        # Actualiza el tag en values.yaml
        sed -i "s/tag: .*/tag: latest/" ApiHelm-chart/values.yaml
        
        cd ApiHelm-chart
        git config --global user.email "sebas99cp@gmail.com.com"
        git config --global user.name "Sebastian Cardozo Padilla"
        git add Chart.yaml values.yaml
        git commit -m "Update chart version to $NEW_VERSION and Docker image tag to latest"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
